
CREATE TABLE LISTING(
  LISTING_ID VARCHAR(36) PRIMARY KEY,
  LISTNAME VARCHAR(20) NOT NULL
);

CREATE TABLE LISTITEM(
  LISTITEM_ID VARCHAR(36) PRIMARY KEY,
  LISTITEM_NAME VARCHAR(20) NOT NULL,
  LISTING_ID VARCHAR(36)
);